config/routes.rb
NetworkerApp::Application.routes.draw do
  resources :users do

    resources :events, only: [:index] do
      post 'search', :on => :collection
      get 'search', :on => :collection
    end

    resources :groups, only: [:index] do 
      post 'search', :on => :collection
    end 

    resources :liusers, only: [:index] do 
      post 'search', :on => :collection
      get 'search', :on => :collection
    end


    resources :tasks, :tokens, :connections 
  end 

  root "welcome#index"
  get "about", to: "welcome#about"
  
  get "/users/:id/lilist", to: "liusers#list"
  post "/liusers", to: "liusers#create"

  get "/sessions", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  post "/sessions/superuser", to: "sessions#superuser"
  delete "/sessions", to: "sessions#destroy"
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks
  has_many :connections
  has_many :tokens
  validates :email, presence: true, uniqueness: true

  self.has_secure_password()
  

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include FinduserHelper
  
  before_action(:find_user, {only: [:edit, :index ,:update, :show, :destroy] })

  def new 
    @user = User.new
    render(:new)
  end 

  def create
    @user = User.new(user_params)
    if @user.save
      session["user_id"]=@user.id
      redirect_to user_path(@user)
    else
      render(:new)
    end 
  end 

  def index
    if current_user.superuser == true
      @users = User.all
      render(:index)    
    else 
      redirect_to user_path(session["user_id"])
    end
  end 

  def edit
  end 

  def update
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end 

  def destroy
    @user.destroy
    redirect_to(:back)
  end 

  def show
    @tasks = Task.where(user_id: params[:id])
    @tasks = @tasks.order(:due_date)
    @connections_connector = Connection.where("user_id = ? AND c_type = ?", params[:id], "Connector")
    @connections_mentor = Connection.where("user_id = ? AND c_type = ?", params[:id], "Mentor")
    @connections_peer = Connection.where("user_id = ? AND c_type = ?", params[:id], "Peer")

    @task = Task.new
    @connection = Connection.new
    if current_user.superuser || current_user.id == params[:id].to_i
      render(:show)
    else  
      redirect_to user_path(current_user.id)
    end 
  
  end 

  
   def authenticate
    unless logged_in?
      redirect_to login_path
    end
  end

  def authorize
    unless current_user == @user
      redirect_to login_path
    end
  end

private
  def user_params
    params.require(:user).permit(:name, :title, :email, :password, :password_confirmation)
  end 
 

end 

app/views/users/_connectionform.html.erb
Manually Add New Connections
<%= form_for [@user, @connection] do |f| %>
  <br \>
  <%= f.label :c_type, ('Connection Type') %>
  <%= f.select :c_type, options_for_select(["Connector","Mentor","Peer"]) %> 
  <br \>
  <%= f.label :name %>
  <%= f.text_field :name %> 
  <br \>
  <%= f.submit %> 
<% end %>

app/views/users/_connectiontable.html.erb
<table >
  <tr>
    <th></th>
    <th></th>
    <th>Type</th>
    <th>Name</th>
    <th></th>
  </tr>
  <% @connections.each do |connection| %>
  <tr>
    <td><%=link_to image_tag("delete.png",size: "21x21"), user_connection_path(params[:id],connection.id), method: "delete" %></td>
    <td>
    <%if connection.photo_url ==""%>
    <%= image_tag("default_photo.jpg", size: "80x80") %>
    <%else%>
    <img src="<%=connection.photo_url%>" height="80" width="80">
    <%end%>
    </td>
    <td><%=connection.c_type%></td>
    <td><%=link_to connection.name, edit_user_connection_path(params[:id],connection.id ) %></td>
    <td><%= link_to image_tag("coffee.png", size:"21x21"), user_tasks_path(params[:id], :title=>("Catch Up: "+connection.name), :due_date=>(Time.now+14.days) ), method: "post" %></td>
  </tr> 
  <% end %>
</table>

app/views/users/_connectiontiles.html.erb
<%@connections.each do |connection| %>

<div id="connection_tile">
  <div id="tile_photo">
    <%if connection.photo_url ==""%>
    <%= image_tag("default_photo.jpg", size: "100x100") %>
    <%else%>
     <img src="<%=connection.photo_url%>" height="100" width="100">
    <%end%>
  </div>
  <div id="tile_details">
    <%=connection.name%> <br \>
    CEO <br \>
    Last Connection <br \>
  </div>
  <div id="tile_coffee">
    <%= link_to image_tag("coffee.png", size:"21x21")+"Create Task to Catch Up", user_tasks_path(params[:id], :title=>("Catch Up: "+connection.name), :due_date=>(Time.now+14.days) ), method: "post" %>

  </div>
</div>




<%end%>

app/views/users/_connectiontiles_connectors.html.erb
<%@connections_connector.each do |connection| %>

<div id="connection_tile">
  <div id="tile_photo">
    <%if connection.photo_url ==""%>
    <%= image_tag("default_photo.jpg", size: "100x100") %>
    <%else%>
     <img src="<%=connection.photo_url%>" height="100" width="100">
    <%end%>
  </div>
  <div id="tile_details">
    <%=connection.name%> <br \>
    CEO <br \>
    Last Connection <br \>
  </div>
  <div id="tile_coffee">
    <%= link_to image_tag("coffee.png", size:"21x21")+"Create Task to Catch Up", user_tasks_path(params[:id], :title=>("Catch Up: "+connection.name), :due_date=>(Time.now+14.days) ), method: "post" %>

  </div>
</div>




<%end%>

app/views/users/_connectiontiles_mentors.html.erb
<%@connections_mentor.each do |connection| %>

<div id="connection_tile">
  <div id="tile_photo">
    <%if connection.photo_url ==""%>
    <%= image_tag("default_photo.jpg", size: "100x100") %>
    <%else%>
     <img src="<%=connection.photo_url%>" height="100" width="100">
    <%end%>
  </div>
  <div id="tile_details">
    <%=connection.name%> <br \>
    CEO <br \>
    Last Connection <br \>
  </div>
  <div id="tile_coffee">
    <%= link_to image_tag("coffee.png", size:"21x21")+"Create Task to Catch Up", user_tasks_path(params[:id], :title=>("Catch Up: "+connection.name), :due_date=>(Time.now+14.days) ), method: "post" %>

  </div>
</div>




<%end%>

app/views/users/_connectiontiles_peers.html.erb
<%@connections_peer.each do |connection| %>

<div id="connection_tile">
  <div id="tile_photo">
    <%if connection.photo_url ==""%>
    <%= image_tag("default_photo.jpg", size: "100x100") %>
    <%else%>
     <img src="<%=connection.photo_url%>" height="100" width="100">
    <%end%>
  </div>
  <div id="tile_details">
    <%=connection.name%> <br \>
    CEO <br \>
    Last Connection <br \>
  </div>
  <div id="tile_coffee">
    <%= link_to image_tag("coffee.png", size:"21x21")+"Create Task to Catch Up", user_tasks_path(params[:id], :title=>("Catch Up: "+connection.name), :due_date=>(Time.now+14.days) ), method: "post" %>

  </div>
</div>




<%end%>

app/views/users/_taskfigure.html.erb
<% @tasks.each do |task| %>
  <div id="taskfigure">
    <div id="taskfigure_pic">
      
    </div>
    <div id="taskfigure_info">
      <%=link_to task.title, edit_user_task_path(params[:id], task.id)%> <br />
      <span id="notes"><%=task.notes %> </span>
    </div>
      <div id="taskfigure_date">
      <%=task.due_date.strftime("%m-%d-%Y")%>
    </div>
  </div>
<% end %>

app/views/users/_taskform.html.erb
<div id="task_form">
  <%= form_for [@user, @task] do |f| %>
  <!--   <%= f.label :t_type, ('Task Type') %>
    <%= f.select :t_type, options_for_select(["Discovery","Radar","Service"])%>
   -->
    <div id="form_1"></div>
    <div id="form_2">
      <%= f.label :title %> <br \>
      <%= f.text_field :title, :placeholder => "Catch Up:  Tom Jones" %>
      <br />
      <%= f.label :notes %> <br \>
      <%= f.text_field :notes, :placeholder => "Discuss his new Job"%>
      <br />
    </div>
    <div id="form_3">
      <%= f.label :due_date %> <br \>
      <%= f.datetime_field :due_date, :placeholder => Time.now+ 14.days %>
    </div>
    <div id="form_4">
      <%= f.submit 'Create New Task', :class=>'task_button'%>
    </div>  
  <% end %>
</div>

app/views/users/_tasktable.html.erb
<table >
  <tr>
    <th id="task_delete"></th>
    <th id="task_type">Type</th>
    <th id="task_title">Title</th>
    <th id="task_notes">Notes</th>
    <th id="task_due">Due Date</th>
  </tr>
  <% @tasks.each do |task| %>
  <tr>
    <td><%=link_to image_tag("delete.png",size: "20x20"), user_task_path(params[:id],task.id), method: "delete" %></td>
    <td><%=task.t_type%></td>
    <td><%=link_to task.title, edit_user_task_path(params[:id], task.id)%></td>
    <td><%=task.notes%></td>
    <td><%=task.due_date.strftime("%Y-%m-%d")%></td>
  </tr> 
  <% end %>
</table>

app/views/users/_userform.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name%>:
  <%= f.text_field :name%> <br \>

  <%= f.label :title%>:
  <%= f.text_field :title%> <br \>

  <%= f.label :email%>:
  <%= f.text_field :email%> <br \>

  <%= f.label :password%>:
  <%= f.password_field :password%> <br \>

  <%= f.label :password_confirmation%>:
  <%= f.password_field :password_confirmation%> <br \>  

  <%= f.submit %> <br \>
<% end %> 

app/views/users/edit.html.erb
<h1><%= @user.name %></h1>

<%=render "userform" %>

app/views/users/index.html.erb
<h1> Admin User Page </h1>
<table class="user">
  <tr>
    <th></th>
    <th></th>
    <th>Name </th>
    <th></th>
    <th>Title </th>
    <th></th>
  </tr>
  <% @users.each do |user| %>
  <tr>
    <td><%=link_to image_tag("delete.png",size: "20x20"), user_path(user.id), method: "delete" %></td>
    <td>
      <%if user.photo_url ==""%>
       <%= image_tag("default_photo.jpg", size: "80x80") %>
      <%else%>
       <img src="<%=user.photo_url%>" width="80" height="80">
      <%end%>
    </td> 
    <td><%=link_to user.name, user_path(user.id) %></td>
    <td><%=link_to image_tag("edit.png"), edit_user_path(user.id) %></td>
    <td><%=user.title%></td>
    <td><%=link_to "SuperUser", sessions_superuser_path(:user_id=> user.id), method: "post"%></td>
  </tr> 
  <% end %>
</table>

app/views/users/new.html.erb
<% if !@user.nil? && @user.id.nil? %>
  <div id="errors">
    <ul>
      <% @user.errors.messages.each do |field,error| %>
        <li><em><%= "#{field.capitalize} #{error.first}!" %></em></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%=render "userform" %>

app/views/users/show.html.erb
<div id="dash_wrapper">
  <div id="person_header">
    <h1>  
      <%if @user.photo_url ==""%>
        <%= image_tag("default_photo.jpg", size: "80x80") %>
        <%else%>
         <img src="<%=@user.photo_url%>" width="80" height="80">
      <%end%>
      <%=@user.name%>
      <%=link_to image_tag("edit.png"), edit_user_path(@user.id)%>
    </h1>
  </div>

  <div id="action_panel">
    <div id="task_panel">
      <div class="task_table">
        <h2>User Tasks: </h2>
        <%= render "taskfigure" %>
        <%= render "taskform" %>        
      </div>
      <div class="hint">
        <div class="hint_border"><h4>HINT:</h4></div> 
        <div class="hint_body">
          <p>Network to identity opportunities</p>
          <p>Create Actionable Tasks for you to reach your goals</p>
        </div>
      </div>
    </div>
    <div id="connection_panel">
    <h2>User Connections:</h2> 
      <div class="connection_table">
        <h3>Connectors</h3>
        <%= render "connectiontiles_connectors" %>
        <h3>Mentors</h3>
        <%= render "connectiontiles_mentors" %>
        <h3>Peers</h3>
        <%= render "connectiontiles_peers" %>
      </div>
      <div class="hint">
        <div class="hint_border"><h4>HINT:</h4></div> 
        <div class="hint_body">
          <p>CONNECTORS will introduce you to other hiring managers.  (Think Former Bosses)</p>
          <p>MENTORS have formerly done your job and are now doing the job you want.  Look to them for career path guidance.</p>
          <p>PEERs currently do the same job as you.  Look to them to develop your craft.</p>
        </div>
      </div>
    </div>  
  </div>

  <div id="nav_panel">
    <div class="partner">
      Search our Partners: 
      <%=link_to image_tag("meetup.png"), user_events_path(@user.id) %>
    </div> 
    <%= render "connectionform" %>
    <div class="partner">
      Search our Partners: 
      <a href="/users/<%= @user.id %>/liusers"><%=image_tag("LinkedIn.png", size: "30x30")%></a>
      <%=link_to image_tag("meetup.png"), user_groups_path(@user.id) %>
    </div>
  </div>

</div>