config/routes.rb
NetworkerApp::Application.routes.draw do
  resources :users do

    resources :events, only: [:index] do
      post 'search', :on => :collection
      get 'search', :on => :collection
    end

    resources :groups, only: [:index] do 
      post 'search', :on => :collection
    end 

    resources :liusers, only: [:index] do 
      post 'search', :on => :collection
      get 'search', :on => :collection
    end


    resources :tasks, :tokens, :connections 
  end 

  root "welcome#index"
  get "about", to: "welcome#about"
  
  get "/users/:id/lilist", to: "liusers#list"
  post "/liusers", to: "liusers#create"

  get "/sessions", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  post "/sessions/superuser", to: "sessions#superuser"
  delete "/sessions", to: "sessions#destroy"
  

end

app/models/liuser.rb
class Liuser < ActiveRecord::Base
  has_many :connections
end 

app/controllers/liusers_controller.rb
class LiusersController < ApplicationController
  before_action(:retrieve_token, {only: [:index, :search] })
  before_action(:add_token, {only: [:index] })
  
  def index

    @connections = Liuser.joins(:connections).where('connections.user_id' => session[:user_id])
  end 

  def create
  end   

  def search
    @response = HTTParty.get("https://api.linkedin.com/v1/people/~/connections?format=json&oauth2_access_token=#{@token}")
    @response = @response["values"]
    
    @response.each do |liuser|
      if liuser["location"].nil?
        @location = " "
      else @location = liuser["location"]["name"] 
      end 

      if liuser["siteStandardProfileRequest"].nil?
        @url = " "
      else @url = liuser["siteStandardProfileRequest"]["url"]
      end 

      if Liuser.find_by(linkedin_id: liuser["id"]).nil?
        li = Liuser.create(
            linkedin_id: liuser["id"], 
            first_name: liuser["firstName"], 
            last_name: liuser["lastName"], 
            headline: liuser["headline"], 
            industry: liuser["industry"], 
            picture_url: liuser["pictureUrl"],
            location: @location,
            li_url: @url
            ) 
        Connection.create(name: (liuser["firstName"]+" "+liuser["lastName"]), c_type: "NONE", user_id: session[:user_id], photo_url: liuser["pictureUrl"], liuser_id: li.id )
      end 
    end 

    render(:search)
  end 

  private

  def add_token
    if params["code"]
      consumer_key = LI_CONSUMER_KEY
      consumer_secret = LI_CONSUMER_SECRET
      @token = HTTParty.get("https://www.linkedin.com/uas/oauth2/accessToken?grant_type=authorization_code&code=#{params["code"]}&redirect_uri=http://localhost:3000/users/#{session["user_id"]}/liusers&client_id=#{consumer_key}&client_secret=#{consumer_secret}" )
      

      Token.create(
      access_date: Time.now,
      expires_in: Time.now + @token["expires_in"],
      access_token: @token["access_token"],
      user_id: params[:user_id]
      )  
    end
  end 

  def retrieve_token
    @token = Token.where("user_id = ? AND expires_in > ?",  params[:user_id], Time.now)
    @token = @token.last
    if !@token.nil?
      @token = @token.access_token
    end 
  end

end 

app/views/liusers/index.html.erb
<h1>Linked In Connections:</h1>

<h3>Refresh Your LinkedIn Connections</h3>
<%if @token.nil? %>
  <%consumer_key = LI_CONSUMER_KEY%>
  <%consumer_secret = LI_CONSUMER_SECRET %>
  <a href="https://www.linkedin.com/uas/oauth2/authorization?response_type=code&client_id=<%=consumer_key%>&state=DCEEFWF45453sdffef424&redirect_uri=http://localhost:3000/users/<%=session[:user_id]%>/liusers">Sign in through Linked In</a>
<%elsif @token%>
  <%=link_to "Fetch Linked In Contacts", search_user_liusers_path(params[:user_id]), method:"post" %>
<%end%>



<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>


<%unless @connections.nil? %>
<table >
  <tr>
    <th></th>
    <th>Name</th>
    <th>Location<th>
    <th>Headline</th>
    <th><th>
    <th><th>
    <th><th>
    <th><th>
  </tr>
  <% @connections.each do |connection| %>
    <tr>
      <td><img src="<%=connection.picture_url%>"></td>
      <td>
        <%if connection.li_url.nil?%>
          <%=connection.first_name+' '+connection.last_name%>
        <%else%>
          <%=link_to connection.first_name+' '+connection.last_name, connection.li_url%>
        <%end%>
      </td>
      <td>
        <%=connection.location%>
      </td>
      <td><%=connection.headline%></td>
      <td><%= link_to "Connector",user_connections_path(params[:user_id], 
            :connection=>{
              :name=>(connection.first_name), 
              :photo_url=>connection.picture_url, 
              :c_type=>"Connector"
            }
       ), method: "post" %></td>
      <td><%= link_to "Mentor", user_connections_path(params[:user_id],
         :connection=>{
              :name=>(connection.first_name), 
              :photo_url=>connection.picture_url, 
              :c_type=>"Mentor"
            }
       ), method: "post" %></td>
      <td><%= link_to "Peer", user_connections_path(params[:user_id], 
        :connection=>{
              :name=>(connection.first_name), 
              :photo_url=>connection.picture_url, 
              :c_type=>"Peer"
            }
       ), method: "post" %></td>
    </tr> 
    <% end %>
  </table>
<%end%>

app/views/liusers/search.html.erb
<h1>Linked In Connections:</h1>


<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>


<%unless @response.nil? %>
<table >
  <tr>
    <th></th>
    <th>Name</th>
    <th>Location<th>
    <th>Headline</th>
    <th><th>
    <th><th>
    <th><th>
    <th><th>
  </tr>
  <% @response.each do |liuser| %>
    <tr>
      <td><img src="<%=liuser["pictureUrl"]%>"></td>
      <td>
        <%if liuser["siteStandardProfileRequest"].blank?%>
          <%=liuser["firstName"]+" "+liuser["lastName"]%>
        <%else%>
          <%=link_to liuser["firstName"]+" "+liuser["lastName"], liuser["siteStandardProfileRequest"]["url"]%>

        <%end%>
      </td>
      <td>
        <%if liuser["location"].blank?%>
          <%="No Location Provided"%>
        <%else%>
          <%=liuser["location"]["name"]%>

        <%end%>
      </td>
      <td><%=liuser["headline"]%></td>
      <td><%= link_to "Connector",user_connections_path(params[:user_id], 
            :connection=>{
              :name=>(liuser["firstName"]+" "+liuser["lastName"]), 
              :photo_url=>liuser["pictureUrl"], 
              :c_type=>"Connector"
            }
       ), method: "post" %></td>
      <td><%= link_to "Mentor", user_connections_path(params[:user_id],
         :connection=>{
              :name=>(liuser["firstName"]+" "+liuser["lastName"]), 
              :photo_url=>liuser["pictureUrl"], 
              :c_type=>"Mentor"
            }
       ), method: "post" %></td>
      <td><%= link_to "Peer", user_connections_path(params[:user_id], 
        :connection=>{
              :name=>(liuser["firstName"]+" "+liuser["lastName"]), 
              :photo_url=>liuser["pictureUrl"], 
              :c_type=>"Peer"
            }
       ), method: "post" %></td>
    </tr> 
    <% end %>
  </table>
<%end%>  