config/routes.rb
NetworkerApp::Application.routes.draw do
  resources :users do

    resources :events, only: [:index] do
      post 'search', :on => :collection
      get 'search', :on => :collection
    end

    resources :groups, only: [:index] do 
      post 'search', :on => :collection
    end 

    resources :liusers, only: [:index] do 
      post 'search', :on => :collection
      get 'search', :on => :collection
    end


    resources :tasks, :tokens, :connections 
  end 

  root "welcome#index"
  get "about", to: "welcome#about"
  
  get "/users/:id/lilist", to: "liusers#list"
  post "/liusers", to: "liusers#create"

  get "/sessions", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  post "/sessions/superuser", to: "sessions#superuser"
  delete "/sessions", to: "sessions#destroy"
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NetworkerApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div class="global-header">

      <%= link_to "Home", root_path, :class => "links" %> 
      <%= link_to("Dashboard", user_path(session[:user_id]), :class => "links") unless session[:user_id].nil? %> 
      
      <%= link_to("User List", users_path, :class => "links") if session[:superuser]==true %>
      <%= link_to "About Us", about_path, :class => "links"  %> 


      <div id="sign_in">
      <%= (render :partial =>"sessions/sign_in", :class=>"links") if session[:user_id].nil?%>

      <%= link_to("Logout #{User.find_by(id: session[:user_id]).name}", sessions_path, :class => "links", method: "delete") unless session[:user_id].nil? %>

      <%= session[:superuser_name] unless session[:superuser_name].nil? %>
      </div>
   
  </div>

</header>


<%= yield %>

</body>
</html>